# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalysisDesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1002)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.SelectionWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.SelectionWidget.setObjectName("SelectionWidget")
        self.AnalysisTab = QtWidgets.QWidget()
        self.AnalysisTab.setObjectName("AnalysisTab")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.AnalysisTab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1010, 300, 451, 401))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.estimateLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.estimateLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.estimateLayout.setContentsMargins(0, 0, 0, 0)
        self.estimateLayout.setObjectName("estimateLayout")
        self.formLayoutWidget = QtWidgets.QWidget(self.AnalysisTab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(1070, 80, 331, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(2)
        self.formLayout.setVerticalSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.label_numPSF = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_numPSF.setObjectName("label_numPSF")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_numPSF)
        self.spinBox_donuts = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_donuts.setProperty("value", 4)
        self.spinBox_donuts.setDisplayIntegerBase(10)
        self.spinBox_donuts.setObjectName("spinBox_donuts")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_donuts)
        self.label_SBR = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_SBR.setObjectName("label_SBR")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_SBR)
        self.lineEdit_sbr = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_sbr.setObjectName("lineEdit_sbr")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sbr)
        self.label_winlen = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_winlen.setObjectName("label_winlen")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_winlen)
        self.lineEdit_winlen = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_winlen.setObjectName("lineEdit_winlen")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_winlen)
        self.label_lifetime_window_i = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_lifetime_window_i.setObjectName("label_lifetime_window_i")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_lifetime_window_i)
        self.lineEdit_lifetimewin_i = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_lifetimewin_i.setObjectName("lineEdit_lifetimewin_i")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_lifetimewin_i)
        self.label_lifetime_window_f = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_lifetime_window_f.setObjectName("label_lifetime_window_f")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_lifetime_window_f)
        self.lineEdit_lifetimewin_f = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_lifetimewin_f.setObjectName("lineEdit_lifetimewin_f")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_lifetimewin_f)
        self.testButton = QtWidgets.QPushButton(self.AnalysisTab)
        self.testButton.setGeometry(QtCore.QRect(1030, 10, 112, 34))
        self.testButton.setObjectName("testButton")
        self.line = QtWidgets.QFrame(self.AnalysisTab)
        self.line.setGeometry(QtCore.QRect(0, 420, 991, 1))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comLabel = QtWidgets.QLabel(self.AnalysisTab)
        self.comLabel.setGeometry(QtCore.QRect(1010, 730, 441, 131))
        self.comLabel.setObjectName("comLabel")
        self.EstimatorButton = QtWidgets.QPushButton(self.AnalysisTab)
        self.EstimatorButton.setGeometry(QtCore.QRect(1150, 250, 171, 34))
        self.EstimatorButton.setObjectName("EstimatorButton")
        self.PSFgroupBox = QtWidgets.QGroupBox(self.AnalysisTab)
        self.PSFgroupBox.setGeometry(QtCore.QRect(10, 0, 981, 441))
        self.PSFgroupBox.setObjectName("PSFgroupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.PSFgroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(570, 20, 401, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.psfLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.psfLayout.setContentsMargins(0, 0, 0, 0)
        self.psfLayout.setObjectName("psfLayout")
        self.psfScrollbar = QtWidgets.QScrollBar(self.PSFgroupBox)
        self.psfScrollbar.setEnabled(False)
        self.psfScrollbar.setGeometry(QtCore.QRect(570, 400, 401, 16))
        self.psfScrollbar.setMaximum(19)
        self.psfScrollbar.setPageStep(1)
        self.psfScrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.psfScrollbar.setObjectName("psfScrollbar")
        self.PSFfile_groupBox = QtWidgets.QGroupBox(self.PSFgroupBox)
        self.PSFfile_groupBox.setGeometry(QtCore.QRect(10, 30, 541, 221))
        self.PSFfile_groupBox.setObjectName("PSFfile_groupBox")
        self.psfFileEditBox = QtWidgets.QLineEdit(self.PSFfile_groupBox)
        self.psfFileEditBox.setGeometry(QtCore.QRect(20, 50, 489, 25))
        self.psfFileEditBox.setObjectName("psfFileEditBox")
        self.browseFilePSF = QtWidgets.QPushButton(self.PSFfile_groupBox)
        self.browseFilePSF.setGeometry(QtCore.QRect(140, 80, 271, 34))
        self.browseFilePSF.setObjectName("browseFilePSF")
        self.PSFmode_groupBox = QtWidgets.QGroupBox(self.PSFfile_groupBox)
        self.PSFmode_groupBox.setGeometry(QtCore.QRect(40, 120, 239, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PSFmode_groupBox.sizePolicy().hasHeightForWidth())
        self.PSFmode_groupBox.setSizePolicy(sizePolicy)
        self.PSFmode_groupBox.setObjectName("PSFmode_groupBox")
        self.radioButton_exppsf = QtWidgets.QRadioButton(self.PSFmode_groupBox)
        self.radioButton_exppsf.setGeometry(QtCore.QRect(50, 60, 161, 20))
        self.radioButton_exppsf.setObjectName("radioButton_exppsf")
        self.radioButton_psffit = QtWidgets.QRadioButton(self.PSFmode_groupBox)
        self.radioButton_psffit.setGeometry(QtCore.QRect(50, 30, 101, 23))
        self.radioButton_psffit.setChecked(True)
        self.radioButton_psffit.setObjectName("radioButton_psffit")
        self.layoutWidget = QtWidgets.QWidget(self.PSFfile_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(320, 131, 181, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.LoadPSFButton = QtWidgets.QPushButton(self.layoutWidget)
        self.LoadPSFButton.setObjectName("LoadPSFButton")
        self.verticalLayout_5.addWidget(self.LoadPSFButton)
        self.pushButton_saveFit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_saveFit.setObjectName("pushButton_saveFit")
        self.verticalLayout_5.addWidget(self.pushButton_saveFit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.TCSPCfile_groupBox = QtWidgets.QGroupBox(self.PSFgroupBox)
        self.TCSPCfile_groupBox.setGeometry(QtCore.QRect(10, 260, 541, 131))
        self.TCSPCfile_groupBox.setObjectName("TCSPCfile_groupBox")
        self.tcspcEditBox = QtWidgets.QLineEdit(self.TCSPCfile_groupBox)
        self.tcspcEditBox.setEnabled(True)
        self.tcspcEditBox.setGeometry(QtCore.QRect(30, 40, 489, 25))
        self.tcspcEditBox.setMouseTracking(False)
        self.tcspcEditBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tcspcEditBox.setObjectName("tcspcEditBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.TCSPCfile_groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 70, 489, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.browseFileTCSPC = QtWidgets.QPushButton(self.layoutWidget1)
        self.browseFileTCSPC.setObjectName("browseFileTCSPC")
        self.horizontalLayout_2.addWidget(self.browseFileTCSPC)
        self.LoadTCSPCButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.LoadTCSPCButton.setObjectName("LoadTCSPCButton")
        self.horizontalLayout_2.addWidget(self.LoadTCSPCButton)
        self.TCSPCgroupBox = QtWidgets.QGroupBox(self.AnalysisTab)
        self.TCSPCgroupBox.setGeometry(QtCore.QRect(10, 450, 991, 451))
        self.TCSPCgroupBox.setObjectName("TCSPCgroupBox")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.TCSPCgroupBox)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(20, 60, 141, 80))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_saveOntimes = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.pushButton_saveOntimes.setObjectName("pushButton_saveOntimes")
        self.verticalLayout_6.addWidget(self.pushButton_saveOntimes)
        self.PushButton_LoadOntimes = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.PushButton_LoadOntimes.setObjectName("PushButton_LoadOntimes")
        self.verticalLayout_6.addWidget(self.PushButton_LoadOntimes)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.TCSPCgroupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 20, 791, 411))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.tcspcLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.tcspcLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.tcspcLayout.setContentsMargins(0, 0, 0, 0)
        self.tcspcLayout.setObjectName("tcspcLayout")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.TCSPCgroupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 161, 99))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_NP = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_NP.setChecked(True)
        self.radioButton_NP.setObjectName("radioButton_NP")
        self.buttonGroup_tcspcmode = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_tcspcmode.setObjectName("buttonGroup_tcspcmode")
        self.buttonGroup_tcspcmode.addButton(self.radioButton_NP)
        self.verticalLayout_2.addWidget(self.radioButton_NP)
        self.radioButton_origami_manual = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_origami_manual.setObjectName("radioButton_origami_manual")
        self.buttonGroup_tcspcmode.addButton(self.radioButton_origami_manual)
        self.verticalLayout_2.addWidget(self.radioButton_origami_manual)
        self.radioButton_origami_auto = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_origami_auto.setObjectName("radioButton_origami_auto")
        self.buttonGroup_tcspcmode.addButton(self.radioButton_origami_auto)
        self.verticalLayout_2.addWidget(self.radioButton_origami_auto)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.TCSPCgroupBox)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 290, 171, 99))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_TraceSelection = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_TraceSelection.setChecked(False)
        self.checkBox_TraceSelection.setObjectName("checkBox_TraceSelection")
        self.verticalLayout_3.addWidget(self.checkBox_TraceSelection)
        self.pushButton_addWindow = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_addWindow.setEnabled(False)
        self.pushButton_addWindow.setObjectName("pushButton_addWindow")
        self.verticalLayout_3.addWidget(self.pushButton_addWindow)
        self.SelectionWidget.addTab(self.AnalysisTab, "")
        self.SimulationTab = QtWidgets.QWidget()
        self.SimulationTab.setObjectName("SimulationTab")
        self.SelectionWidget.addTab(self.SimulationTab, "")
        self.gridLayout.addWidget(self.SelectionWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionOne = QtWidgets.QAction(MainWindow)
        self.actionOne.setObjectName("actionOne")
        self.actionTwo = QtWidgets.QAction(MainWindow)
        self.actionTwo.setObjectName("actionTwo")
        self.actionThree = QtWidgets.QAction(MainWindow)
        self.actionThree.setObjectName("actionThree")
        self.actionFour = QtWidgets.QAction(MainWindow)
        self.actionFour.setObjectName("actionFour")
        self.actionFive = QtWidgets.QAction(MainWindow)
        self.actionFive.setObjectName("actionFive")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")

        self.retranslateUi(MainWindow)
        self.SelectionWidget.setCurrentIndex(0)
        self.LoadPSFButton.clicked.connect(MainWindow.fit_exppsf)
        self.LoadTCSPCButton.clicked.connect(MainWindow.load_tcspc)
        self.browseFileTCSPC.clicked.connect(MainWindow.select_tcspc)
        self.browseFilePSF.clicked.connect(MainWindow.select_exppsf)
        self.psfScrollbar.valueChanged['int'].connect(MainWindow.update_image)
        self.pushButton_addWindow.clicked.connect(MainWindow.region_selection)
        self.testButton.clicked.connect(MainWindow.read_ontimes)
        self.checkBox_TraceSelection.toggled['bool'].connect(MainWindow.check_tcspcmode)
        self.EstimatorButton.clicked.connect(MainWindow.position_estimation)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analysis"))
        self.label_numPSF.setText(_translate("MainWindow", "# of donut positions"))
        self.label_SBR.setText(_translate("MainWindow", "SBR"))
        self.lineEdit_sbr.setText(_translate("MainWindow", "30"))
        self.label_winlen.setText(_translate("MainWindow", "Window length"))
        self.lineEdit_winlen.setText(_translate("MainWindow", "0.1"))
        self.label_lifetime_window_i.setText(_translate("MainWindow", "Lifetime init in ns"))
        self.lineEdit_lifetimewin_i.setText(_translate("MainWindow", "0"))
        self.label_lifetime_window_f.setText(_translate("MainWindow", "Lifetime crop in ns"))
        self.lineEdit_lifetimewin_f.setText(_translate("MainWindow", "2"))
        self.testButton.setText(_translate("MainWindow", "test"))
        self.comLabel.setText(_translate("MainWindow", "TextLabel"))
        self.EstimatorButton.setText(_translate("MainWindow", "Estimate Position"))
        self.PSFgroupBox.setTitle(_translate("MainWindow", "PSF selection"))
        self.PSFfile_groupBox.setTitle(_translate("MainWindow", "PSF file selection"))
        self.browseFilePSF.setText(_translate("MainWindow", "Browse File"))
        self.PSFmode_groupBox.setTitle(_translate("MainWindow", "PSF type"))
        self.radioButton_exppsf.setText(_translate("MainWindow", "Experimental PSF"))
        self.radioButton_psffit.setText(_translate("MainWindow", "PSF fit"))
        self.LoadPSFButton.setText(_translate("MainWindow", "Fit PSF"))
        self.pushButton_saveFit.setText(_translate("MainWindow", "Save Fit"))
        self.TCSPCfile_groupBox.setTitle(_translate("MainWindow", "TCSPC file selection"))
        self.browseFileTCSPC.setText(_translate("MainWindow", "Browse File"))
        self.LoadTCSPCButton.setText(_translate("MainWindow", "Load TCSPC"))
        self.TCSPCgroupBox.setTitle(_translate("MainWindow", "TCSPC panel"))
        self.pushButton_saveOntimes.setText(_translate("MainWindow", "Save On-times"))
        self.PushButton_LoadOntimes.setText(_translate("MainWindow", "Load On-times"))
        self.radioButton_NP.setText(_translate("MainWindow", "Nanoparticle"))
        self.radioButton_origami_manual.setText(_translate("MainWindow", "Origami (manual)"))
        self.radioButton_origami_auto.setText(_translate("MainWindow", "Origami (auto)"))
        self.checkBox_TraceSelection.setText(_translate("MainWindow", "Select on times"))
        self.pushButton_addWindow.setText(_translate("MainWindow", "Add window"))
        self.SelectionWidget.setTabText(self.SelectionWidget.indexOf(self.AnalysisTab), _translate("MainWindow", "Analysis"))
        self.SelectionWidget.setTabText(self.SelectionWidget.indexOf(self.SimulationTab), _translate("MainWindow", "Simulation"))
        self.actionOne.setText(_translate("MainWindow", "One"))
        self.actionTwo.setText(_translate("MainWindow", "Two"))
        self.actionThree.setText(_translate("MainWindow", "Three"))
        self.actionFour.setText(_translate("MainWindow", "Four"))
        self.actionFive.setText(_translate("MainWindow", "Five"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

